### ISSUE TITLE
Fails to link libpthread on gentoo

### ISSUE THREAD

**Issue by xloem** [pothosware/gnuradio#18]
```
Linking CXX shared library libgnuradio-runtime-3.7.7.1.so
CMakeFiles/gnuradio-runtime.dir/thread/thread.cc.o: In function `gr::thread::thread_bind_to_processor(unsigned long, std::vector<int, std::allocator<int> > const&)':
thread.cc:(.text+0xa0): undefined reference to `pthread_setaffinity_np'
CMakeFiles/gnuradio-runtime.dir/thread/thread.cc.o: In function `gr::thread::thread_unbind(unsigned long)':
thread.cc:(.text+0x4ce): undefined reference to `pthread_setaffinity_np'
CMakeFiles/gnuradio-runtime.dir/thread/thread_body_wrapper.cc.o: In function `gr::thread::mask_signals()':
thread_body_wrapper.cc:(.text+0x101): undefined reference to `pthread_sigmask'
collect2: error: ld returned 1 exit status
gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/build.make:1776: recipe for target 'gnuradio-runtime/lib/libgnuradio-runtime-3.7.7.1.so.0.0.0' failed
make[2]: *** [gnuradio-runtime/lib/libgnuradio-runtime-3.7.7.1.so.0.0.0] Error 1
CMakeFiles/Makefile2:682: recipe for target 'gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/all' failed
make[1]: *** [gnuradio-runtime/lib/CMakeFiles/gnuradio-runtime.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

Stock libgnuradio v3.7.7.1 does not have this issue for me.

**Comment by guruofquality** [comment]
Hmm... The runtime is getting compiled with c++11 because of the modifications -- which might be messing with it. It probably needs -pthread or -lpthread

Sorry about the bindings being out of date. I have been considering having users install a stock gr and then providing a custom gnuradio-runtime only package that matches the ABI. This would make packaging easier for me as well.

**Comment by xloem** [comment]
I found that this is caused by toggling in PothosStandardFlags.cmake:

```
    #force a compile-time error when symbols are missing
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--no-undefined")
```

It looks like gnuradio is already not linking libpthread into libgnuradio-runtime-*.so; pothos just turns it into an error.

**Comment by guruofquality** [comment]
Yea, no-undefined has been very helpful for catching these sort of bugs at compile time. I guess subsequent libraries link pthread so its not an issue. I would fix this here: https://github.com/pothosware/gnuradio/blob/master/gnuradio-runtime/lib/CMakeLists.txt#L154

```
   ########################################################################
    # Link with the thread library
    ########################################################################
    if (UNIX)
        set(CMAKE_THREAD_PREFER_PTHREAD ON)
        find_package(Threads)
        list(APPEND gnuradio_runtime_libs ${CMAKE_THREAD_LIBS_INIT})
    endif()
```

So I do plan on getting around to fixing and testing all of these issues, theres just a lot going on ATM and its easier to respond to the issues quickly than fix and test the bugs. Let me know if you are interested in taking on this or other issues. I am happy to give you commit access, any help is appreciated. Just let me know before doing anything too drastic.

**Comment by xloem** [comment]
This error has disappeared for me after removing sdr-related programs from my system and reinstalling everything from source, with cmake, all into /usr/local

**Comment by guruofquality** [comment]
Cool, and the new organization uses stock gnuradio with a stand-lone modded runtime library. So we should be good. Closing.
