### ISSUE TITLE
Python inspection fail

### ISSUE THREAD

**Issue by gvanem** [pothosware/gnuradio#29]
After downloading the latest Pothos-bundle for x64 (I'm on Win-10), I get the below failure when launching `gnuradio-companion.exe`. Seems it is _ass-u-me_'d Python should be installed from a _.MSI_ file. The first time I've seen a program looking into the Registry to check for Python. My Python 2.7 just works as-is on most cases.
![python27-inspection-failed](https://cloud.githubusercontent.com/assets/945271/19354434/fc60c2aa-9166-11e6-8140-98ae3533d3bd.png)

Furthermore, after downloading the Pothos sources from GitHub, I failed to find any `.cpp` or `.py` file with the above error-message. What gives? 
Maybe I can add this Registry key manually? (I don't dare to reinstall Python 2.7).

**Comment by guruofquality** [comment]
> After downloading the latest Pothos-bundle for x64 (I'm on Win-10), I get the below failure when launching gnuradio-companion.exe. Seems it is ass-u-me'd Python should be installed from a .MSI file. 

Python 27 is one of the post install instructions for grc. Its just not packaged, and its only needed for some of the apps: https://github.com/pothosware/PothosSDR/wiki/GNURadio#installation-instructions

> Furthermore, after downloading the Pothos sources from GitHub, I failed to find any .cpp or .py file with the above error-message. What gives?

Its from this project FWFW:
https://github.com/pothosware/gnuradio-companion-exe

> Maybe I can add this Registry key manually? (I don't dare to reinstall Python 2.7).

I found this to be a standard registry key to discovery python installations. I'm not sure why it may not be working? A python reinstall for making the key manually may work

**Comment by gvanem** [comment]
Okay I manages to add this key manually after some problem; realising I had to run `regedt32` for 64-bit keys. So `gnuradio-companion` and the `GNURadioHelper.py` starts, but with some other issues....

**Comment by guruofquality** [comment]
In that case, was it not a 64-bit version of python?

**Comment by gvanem** [comment]
No it wasn't. My Python 2,7 is 32-bit. 

I understand everything in Photos must be 64-bit. Even the Python due to all the `*.pyd`, no?

**Comment by guruofquality** [comment]
> I understand everything in Photos must be 64-bit. Even the Python due to all the *.pyd, no?

Thats correct. Python must be 64 bit. Many of the python bindings build wrappers against the python 64 bit development environments (gnuradio, soapysdr has swig too, and pothos python bindings).
